SELECT (23+((25-2)/2)*45) AS RESULTADO;

SELECT ceiling(12.3333) AS RESULTADO;

SELECT round(12.3333) AS RESULTADO;

SELECT floor(12.7775225) AS RESULTADO;

SELECT rand() AS RESULTADO;

SELECT NUMERO, QUANTIDADE, PRECO, QUANTIDADE*PRECO AS FATURAMENTO
 FROM itens_notas_fiscais;

SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE*PRECO, 2) AS FATURAMENTO
 FROM itens_notas_fiscais;
