SELECT * FROM produtos;

UPDATE PRODUTOS SET PRECO_LISTA = 5 WHERE CODIGO = '1000889';

UPDATE PRODUTOS SET EMBALAGEM = 'PET', TAMANHO = '1 Litro', DESCRITOR = 'Sabor da Montanha - 1 Litro - Uva'  WHERE CODIGO = '1000889';

SELECT * FROM produtos WHERE SABOR = 'Maracujá';

UPDATE produtos SET PRECO_LISTA = PRECO_LISTA * 1.10 
WHERE SABOR = 'Maracujá';

SELECT * FROM clientes
WHERE CPF = 19290992743;

UPDATE clientes SET ENDERECO = 'R. Jorge Emílio 23', BAIRRO = 'Santo Amaro', CIDADE = 'São Paulo',
ESTADO = 'SP', CEP = '8833223'
WHERE CPF = 19290992743;