CREATE TABLE TAB_IDENTITY (ID INT  AUTO_INCREMENT, DESCRITOR VARCHAR (20), primary key (ID));

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE1');
SELECT * FROM TAB_IDENTITY;

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE2');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE3');
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (NULL, 'CLIENTE4');

DELETE FROM TAB_IDENTITY WHERE ID = 2;

INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (NULL, 'CLIENTE5');

INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (100, 'CLIENTE5');

DELETE FROM TAB_IDENTITY WHERE ID = 5;

INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (NULL, 'CLIENTE6');

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE7');

